<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>사유입력란</name>
   <tag></tag>
   <elementGuidId>77c80a97-111b-4abc-9739-58e8cf89c8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-93</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='mui-93']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e1692956-7364-4661-81b0-30d26447092c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b2adf7f0-5719-40e5-8ee3-ff9b393ebda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d4e6cca-f411-41f9-b1f9-323365e52da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>메시지를 입력하세요.</value>
      <webElementGuid>25af6308-4ae8-4eb5-999f-f61cf394b698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-123ozb2</value>
      <webElementGuid>a22d0636-0220-48f9-aa05-85fbe69ba051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-93</value>
      <webElementGuid>c88d786e-c98a-45b2-a893-8fae84cb3107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STG자동화011</value>
      <webElementGuid>e1d14769-4c90-42dd-bf06-3bd75cb2608c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-93&quot;)</value>
      <webElementGuid>cf3b00bc-6167-44aa-9f1c-d9c97c6905f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mui-93']</value>
      <webElementGuid>79f0cb5a-1fd9-44cd-9175-87f5d7eb9b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::textarea[1]</value>
      <webElementGuid>1611a22b-7ee4-4ad3-bfb9-f4cdb5fdba33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[5]/preceding::textarea[2]</value>
      <webElementGuid>e61a2edc-7ff9-4bab-9bd4-2d8e829e42c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명을 거부하면 더 이상 이 문서에 서명하거나 문서를 볼 수 없어요.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>e631c86c-0c69-416d-b7d8-6cbe95d46be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='STG자동화011']/parent::*</value>
      <webElementGuid>a440d0a4-d7e9-43d7-af34-85deef239d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>34f56e60-ef58-4375-ab17-5bf4e2058425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '메시지를 입력하세요.' and @id = 'mui-93' and (text() = 'STG자동화011' or . = 'STG자동화011')]</value>
      <webElementGuid>63ccf6e2-a4f8-414a-a01d-a03b666cdd9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
