<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명양도_추가정보 입력 필드</name>
   <tag></tag>
   <elementGuidId>f990831d-bcf9-40f5-ac80-6487ac5ecf95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-93</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = '서명 참여자 변경 사유를 입력하세요.']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='mui-93']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>844b4ded-a6b9-492c-a717-1b937c385e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7afd60b9-1616-47d5-9ca1-df72343af355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fe7943ce-f2cb-4427-b64b-c68298ea5d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>서명 참여자 변경 사유를 입력하세요.</value>
      <webElementGuid>0345fa29-842b-49be-b768-61d2ea2ff5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-123ozb2</value>
      <webElementGuid>db2948a6-f7e6-40e6-ac99-932b31b92140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-93</value>
      <webElementGuid>ecf0e82a-2169-4abb-8b0e-7b1b806b1fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-93&quot;)</value>
      <webElementGuid>80bc62f3-bf2a-4ff4-9ba1-428b2236b3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mui-93']</value>
      <webElementGuid>845047c8-e1b5-4be2-8938-76ef0a60ce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b8c7a945-6b69-4876-ab65-680c18e8ed69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '서명 참여자 변경 사유를 입력하세요.' and @id = 'mui-93']</value>
      <webElementGuid>f8540083-7d13-4200-9d05-7810929c7baf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
