<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mui-184</name>
   <tag></tag>
   <elementGuidId>8063e3ed-afdb-4364-9736-263c4cbc1e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-184</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-184']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f33efb5-ff82-46ad-8373-1d0dca6481ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>cdbe0fee-9dae-485f-be1f-cc0756051bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-184</value>
      <webElementGuid>f86ce405-aaad-43b4-a014-71bc6bafc218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTooltip-popper styled__FieldMenuTooltip-sc-5sbb22-2 eAUAVT MuiTooltip-popperInteractive css-1j760ej MuiPopper-root</value>
      <webElementGuid>077f72d1-0b9e-4b9a-ae71-d8b64af0f7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popper-placement</name>
      <type>Main</type>
      <value>top-end</value>
      <webElementGuid>ac45b590-6021-4c4e-91c3-19051ee7f841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-184&quot;)</value>
      <webElementGuid>3b696322-56c9-404d-b51f-3caa71dcfd0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-184']</value>
      <webElementGuid>d1f68d18-922e-4e5c-badf-3e4ccbe2f2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 필드 속성 설정'])[1]/following::div[1]</value>
      <webElementGuid>48c4f616-6867-4d93-9c22-855019114d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mui-184', '&quot;', ')')])[1]/following::div[9]</value>
      <webElementGuid>70245bc1-91b3-4b4b-a389-cdff287aede8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>57673059-6ffb-4725-93ff-db32976718ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-184']</value>
      <webElementGuid>7da6f5ef-f09e-47ca-a134-ccbc15be5316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
