<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mui-173</name>
   <tag></tag>
   <elementGuidId>c6f50aec-acaf-4ca2-a954-6ff8f2b9cc18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-173</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-173']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7f10070-4c6e-46c3-b04d-7ffa57a62a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>f0fa4c5a-e791-4ad4-9611-d5190574b445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-173</value>
      <webElementGuid>16338533-d01d-4d0c-8435-9472e07509ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTooltip-popper styled__FieldMenuTooltip-sc-5sbb22-2 eAUAVT MuiTooltip-popperInteractive css-1j760ej MuiPopper-root</value>
      <webElementGuid>39d79729-acb4-49d0-bb49-d6a82bef2430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popper-placement</name>
      <type>Main</type>
      <value>top-end</value>
      <webElementGuid>eec8a695-83b4-4b4b-95ac-6298e89e46e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-173&quot;)</value>
      <webElementGuid>0395b43b-b953-4edb-8129-8e3303ac76dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-173']</value>
      <webElementGuid>cf0823c5-0d6b-45da-944d-03c2984aaf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 필드 속성 설정'])[1]/following::div[1]</value>
      <webElementGuid>5cd56ad8-bf03-4f38-811c-e591665b28f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mui-173', '&quot;', ')')])[1]/following::div[9]</value>
      <webElementGuid>4ba8b100-60c1-41b7-8961-107c6b1d0511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>c2bdd41d-15f3-4006-a962-2f683013bf9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-173']</value>
      <webElementGuid>ac28a043-3316-4db6-88d6-10dfa0f0eefe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
