<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_123</name>
   <tag></tag>
   <elementGuidId>e1e97286-4f88-4d18-b2a0-5eaf37b7eb38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wrapperThumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapperThumb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11d773c3-a1d5-48f0-b644-a6a6d69d3961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__WrapperThumbnails-sc-1552ps0-3 YzkmU MuiBox-root css-0</value>
      <webElementGuid>370e3b5b-5003-4f2b-ac56-c990538484e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wrapperThumb</value>
      <webElementGuid>76296e92-4622-4d0e-8373-c6d96ffe1710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123</value>
      <webElementGuid>e6f06c23-72b6-4f6d-a3c3-53c761ec2e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapperThumb&quot;)</value>
      <webElementGuid>38100ae1-0c2b-4037-9a4e-f401ad844dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wrapperThumb']</value>
      <webElementGuid>8d2277a6-657f-45a9-8486-59c422288dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='thumbnail-panel']/div/div[2]</value>
      <webElementGuid>7f8209fc-f15f-45b6-8e6e-2939fdc4e2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='발송 전용 문서로 만들기'])[1]/following::div[19]</value>
      <webElementGuid>987acad4-df0f-40a1-9dac-6d3f7bf036fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='내 서명 문서로 만들기'])[1]/following::div[20]</value>
      <webElementGuid>734bea37-e933-46ba-b5f0-936ea0bea9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'wrapperThumb', '&quot;', ')')])[1]/preceding::div[14]</value>
      <webElementGuid>b163229b-e45d-4522-a80e-5fedd9cfc9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]</value>
      <webElementGuid>a2ecd81e-78ac-4f69-8870-0031860ac102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wrapperThumb' and (text() = '123' or . = '123')]</value>
      <webElementGuid>6497b278-85e3-45a2-95e6-c4c5a2dcc98c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
