<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mui-178</name>
   <tag></tag>
   <elementGuidId>34d446f7-c008-4203-a0c2-32d7ec377c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-178</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-178']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b441e73-d552-4aad-a238-a905d71970f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>9ac62e42-9f1e-446f-b3ff-b84b5533e3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-178</value>
      <webElementGuid>7b3e66a8-bb3b-494d-bdc1-e79275a89136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTooltip-popper styled__FieldMenuTooltip-sc-5sbb22-2 eAUAVT MuiTooltip-popperInteractive css-1j760ej MuiPopper-root</value>
      <webElementGuid>0c1f9a6a-13d0-4c5c-9653-faddff4793b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popper-placement</name>
      <type>Main</type>
      <value>top-end</value>
      <webElementGuid>86209fdc-856a-4e39-b5a9-a5b37a48e630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-178&quot;)</value>
      <webElementGuid>545bf53a-7d38-4bc9-a6a1-32ed604058ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-178']</value>
      <webElementGuid>c80d1d02-ce9d-4771-9c63-56f95f95c98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[9]/following::div[1]</value>
      <webElementGuid>e0e49890-921f-4483-a360-ad48652110b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='크기 맞춤'])[1]/following::div[6]</value>
      <webElementGuid>7e02a4fb-1d5a-4e67-bb5c-47c0db64914b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>6d34c735-064a-492c-854c-2481e24829ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-178']</value>
      <webElementGuid>5b0a97bb-ae2d-4266-8113-507f2885084d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
