<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mui-162</name>
   <tag></tag>
   <elementGuidId>7800d7f3-2c99-4e73-8986-8f695da3f6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-162</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-162']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8b13254-f3d2-4fa1-ba8e-4adbb1c841ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88c9c6ef-ffab-4861-8b13-e5a4d6d8228a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>김한컴</value>
      <webElementGuid>760f09f0-d86a-4ed1-bb0f-2a6fe7538c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da7e7669-8f30-4e96-83c4-d994666cbb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-zrzwyc</value>
      <webElementGuid>a31ee7b2-c7b8-4d6b-8242-413c04b82cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>이은지</value>
      <webElementGuid>348fa45f-f997-4393-9b1c-20be72fc90b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-162</value>
      <webElementGuid>9f6e21d6-ce9c-4977-a784-fdca31b7e3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-162&quot;)</value>
      <webElementGuid>669f045c-d914-4f39-a174-75208d01baec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-162']</value>
      <webElementGuid>8cd0efb8-143c-4362-b17a-18963126f9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div[2]/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>ca16a895-0cc5-4f90-bd36-eb531c075467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>6f27967d-9619-4622-998f-2bf67562da15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '김한컴' and @type = 'text' and @id = 'mui-162']</value>
      <webElementGuid>e5114e34-d7b8-4726-bcdd-4a95423f3e5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
