<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mui-145</name>
   <tag></tag>
   <elementGuidId>09432e8e-ccfa-46aa-8d1e-443b3caf0490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-145</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-145']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7aabb74-d892-481c-a00f-20d8580510d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>241bcae8-66a8-4295-9da4-17d61f50273e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>김한컴</value>
      <webElementGuid>e51787ce-6ab3-4ef8-9d26-59287d4db4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a821da8-b8b3-46d3-9b2c-26e40d3793b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-zrzwyc</value>
      <webElementGuid>b7db9946-3c40-4733-bbc5-4f2ef4924d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-145</value>
      <webElementGuid>73c780a5-2e7d-4447-b8b2-d26d3b64dbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-145&quot;)</value>
      <webElementGuid>ad4e03aa-65c7-45c6-a205-47fa3320c9b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-145']</value>
      <webElementGuid>84b149b2-73a1-473f-949a-349d4c719a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>faaa6281-e017-4e42-9fa8-b23235fefb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>807735a8-3fc8-408d-9bc9-7406e75c4bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '김한컴' and @type = 'text' and @id = 'mui-145']</value>
      <webElementGuid>31594397-e4dc-42d7-9aed-0961a736721e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
