<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>bec27150-a80c-4d13-9883-ee18fa6357dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-ke3f99 > svg > g > path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mui-184&quot;)/div[@class=&quot;MuiTooltip-tooltip MuiTooltip-tooltipPlacementTop css-i6gkim&quot;]/div[@class=&quot;styled__IconPanel-sc-5sbb22-0 eExsrU MuiBox-root css-0&quot;]/button[@id=&quot;field_icon_panel_button&quot;]/div[@class=&quot;MuiBox-root css-ke3f99&quot;]/svg[1]/g[1]/path[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>a121bd8b-1b84-4875-a4c0-766be3a723cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>m13.222 7.999 2.24 2.24.041.035L9.878 15.9 6.825 17a.325.325 0 0 1-.325-.325l1.1-2.918c0-.086.034-.17.095-.23l5.527-5.528zm2.365-1.904 1.818 1.818a.325.325 0 0 1 0 .46l-1.131 1.13-.035-.042-2.24-2.239 1.128-1.127a.325.325 0 0 1 .46 0z</value>
      <webElementGuid>9784fd8a-4449-42de-a354-f80f5d62daef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#FFF</value>
      <webElementGuid>70733fcb-5295-43cd-8e1c-0e6e5c8cb44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-184&quot;)/div[@class=&quot;MuiTooltip-tooltip MuiTooltip-tooltipPlacementTop css-i6gkim&quot;]/div[@class=&quot;styled__IconPanel-sc-5sbb22-0 eExsrU MuiBox-root css-0&quot;]/button[@id=&quot;field_icon_panel_button&quot;]/div[@class=&quot;MuiBox-root css-ke3f99&quot;]/svg[1]/g[1]/path[1]</value>
      <webElementGuid>6f2e8783-02d5-4ade-9d91-dc679bb9ade2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#FFF</value>
      <webElementGuid>95578ee1-cd02-4ef5-a5aa-064c071fa0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>87d87107-6f62-4e48-9d8d-2a3378f00a86</webElementGuid>
   </webElementProperties>
</WebElementEntity>
