<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PDF 캔버스</name>
   <tag></tag>
   <elementGuidId>15c31b1a-5dff-4ec5-a7ba-e2a93d68e20e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageContainer1']/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas.react-pdf__Page__canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>e097e436-cd32-4914-999e-f56ef21a255b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-pdf__Page__canvas</value>
      <webElementGuid>6e0af126-b336-4e76-9579-adbf91be79db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1606</value>
      <webElementGuid>76f3f3c0-c987-4386-a132-36c0b678278f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2270</value>
      <webElementGuid>2d5c168d-bb05-4609-b2b7-6554ee33e1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContainer1&quot;)/div[@class=&quot;react-pdf__Page&quot;]/canvas[@class=&quot;react-pdf__Page__canvas&quot;]</value>
      <webElementGuid>3f5ab239-638d-4f6a-898c-5fda673a5a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageContainer1']/div/canvas</value>
      <webElementGuid>afae996b-a74d-4d67-afd6-7eb75f471b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>691f9bc2-5528-4d31-975a-c4db6a53c87e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
