<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>거부 리소스</name>
   <tag></tag>
   <elementGuidId>2cd464e6-b385-45db-bca4-f1aeba27cbe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styled__StatusInner-sc-1f56z8f-1.geZsIK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@type='declined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc72bc61-9531-4131-a98b-e6c7b3fd0ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__StatusInner-sc-1f56z8f-1 geZsIK</value>
      <webElementGuid>36d75593-8306-4641-8233-686eabd93f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>26bdaacd-e090-4fbd-a5dc-497652edbb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2b731e22-b231-4495-8822-94adddfe3f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>거부</value>
      <webElementGuid>72e71ddb-15e6-488d-8179-e0ea0b0ace58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-3vsr9p&quot;]/div[@class=&quot;MuiBox-root css-1ik4laa&quot;]/div[@class=&quot;MuiBox-root css-hpuc4i&quot;]/main[@class=&quot;MuiBox-root css-roxj3j&quot;]/div[@class=&quot;MuiBox-root css-11jivkb&quot;]/div[@class=&quot;MuiBox-root css-1yygsgg&quot;]/div[@class=&quot;MuiBox-root css-1ofqig9&quot;]/div[@class=&quot;MuiBox-root css-1alisiy&quot;]/div[@class=&quot;MuiBox-root css-1m18l0t&quot;]/div[@class=&quot;styled__StatusWrapper-sc-1f56z8f-0 dQfcJg&quot;]/div[@class=&quot;styled__StatusInner-sc-1f56z8f-1 geZsIK&quot;]</value>
      <webElementGuid>2d5c9bcd-9b2f-49cd-818c-85b01263bb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>declined</value>
      <webElementGuid>3f133f38-3139-4be3-8431-81dd28dec9e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='declined']</value>
      <webElementGuid>c0c0636b-eca7-4ad0-8af6-41c9cab5a1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[2]/div/div</value>
      <webElementGuid>e99e2f0e-1113-44b7-aef5-3513ebbdf0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='관리'])[1]/following::div[5]</value>
      <webElementGuid>c620eda7-c233-469a-aace-16e86fc0c0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='일시'])[1]/following::div[6]</value>
      <webElementGuid>3a6e004c-2b79-4fb3-a1aa-04c9cc620c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sample_pdf'])[1]/preceding::div[1]</value>
      <webElementGuid>302de0cf-08d6-418f-940a-5e759a7f7281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='거부']/parent::*</value>
      <webElementGuid>d1bae2ed-1e32-4e36-bcf3-b0f28edb5fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div</value>
      <webElementGuid>a68acc87-3819-4332-8c5a-e7a7dc79c3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'declined' and (text() = '거부' or . = '거부')]</value>
      <webElementGuid>47c27ab0-f735-47ba-9e1b-af8ffff08618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='편집 완료'])[1]/following::div[8]</value>
      <webElementGuid>cc51d737-3a96-49d1-a0ab-76001e2d53a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::div[9]</value>
      <webElementGuid>4a7b1abb-6276-423b-aeed-109532e71993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>7e4ae5f7-157e-4091-95c4-7ec23e1fb749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '편집 종료편집한 내용이 저장되지 않아요. 종료할까요?취소확인' or . = '편집 종료편집한 내용이 저장되지 않아요. 종료할까요?취소확인')]</value>
      <webElementGuid>1c5f10f9-f272-44a2-877f-77cbe3dab777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
