<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>내 서명_ 필드비어있음 체크포인트</name>
   <tag></tag>
   <elementGuidId>93989de9-6e6b-4b49-91ee-a607c2f6247c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styled__Text-sc-1nhdku1-0.jsAyzS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6dcac4dd-4cd6-4dcf-a337-ac9fd579ce12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Text-sc-1nhdku1-0 jsAyzS</value>
      <webElementGuid>ec320c4f-7df5-4629-87db-155edbcacd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>서명 문서에 추가한 필드가 비어 있어요. 필드에 내용을 입력해 주세요.</value>
      <webElementGuid>57b27262-1037-49a2-b61a-b9c8467a45c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-4qljru&quot;]/div[@class=&quot;MuiSnackbar-root MuiSnackbar-anchorOriginTopCenter css-zppt23&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation6 MuiAlert-root MuiAlert-filledWarning MuiAlert-filled css-rjsnrv&quot;]/div[@class=&quot;MuiAlert-message css-wnhfnw&quot;]/div[@class=&quot;styled__Text-sc-1nhdku1-0 jsAyzS&quot;]</value>
      <webElementGuid>16eccd76-f351-44e7-a0e3-7520d2044cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div</value>
      <webElementGuid>f2b2fc27-7fc4-45a6-a513-6323b768faca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='초기화'])[1]/preceding::div[11]</value>
      <webElementGuid>d001f1e0-f0c7-4af6-95e6-146d5348b0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='눈금 보이기'])[1]/preceding::div[14]</value>
      <webElementGuid>dd28d847-8c5c-4890-8577-3ab1f72d41ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='서명 문서에 추가한 필드가 비어 있어요. 필드에 내용을 입력해 주세요.']/parent::*</value>
      <webElementGuid>5905b20c-f7a9-42cd-8019-fa727bc58a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div</value>
      <webElementGuid>83d85449-275c-495d-ae54-e58be14f952b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '서명 문서에 추가한 필드가 비어 있어요. 필드에 내용을 입력해 주세요.' or . = '서명 문서에 추가한 필드가 비어 있어요. 필드에 내용을 입력해 주세요.')]</value>
      <webElementGuid>b59cd5f9-4021-47d5-9536-11456b16f35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
