<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>내 서명_편집 버튼</name>
   <tag></tag>
   <elementGuidId>5e9521e6-79a5-4e90-ae32-f80e9cde1b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Assign-Fields-Edit-GetSignatures</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee009098-923e-4ad3-98d9-307a2151bd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assign-Fields-Edit-GetSignatures</value>
      <webElementGuid>68f70e8b-ee59-4889-b4d6-262c1e1965e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styledCreate__BtnEdit-sc-1e5ee0j-3 eFbBUR</value>
      <webElementGuid>d4cd3e2c-8d0f-456e-b5cf-2fd1f4fa759c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>편집</value>
      <webElementGuid>f8c2e380-9ee5-4d9b-96f2-c7d38199f5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assign-Fields-Edit-GetSignatures&quot;)</value>
      <webElementGuid>7420eb50-281f-4fe3-9802-6a9c0cd55ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      <webElementGuid>cbae96a2-92bf-4662-9321-29266c3dcea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div/div</value>
      <webElementGuid>b11464a2-17b9-427d-bd6e-809874d8d83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='계속'])[1]/following::div[10]</value>
      <webElementGuid>793a1d9c-30ad-42cf-9f38-694a53aaca3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::div[3]</value>
      <webElementGuid>58230f55-4c69-4464-9824-654040b59da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/preceding::div[31]</value>
      <webElementGuid>aa553875-b4e6-4e6c-aff9-4c4dc251cb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='편집']/parent::*</value>
      <webElementGuid>e1b746f2-a50f-4577-b43c-1904995cde1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div</value>
      <webElementGuid>0048c826-3e6e-4e82-825b-176033ad3a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Assign-Fields-Edit-GetSignatures' and (text() = '편집' or . = '편집')]</value>
      <webElementGuid>3786aca1-ddc1-4d56-96ef-478f423330f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
