<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>내 서명_좌측 메뉴</name>
   <tag></tag>
   <elementGuidId>47ded3d3-96e9-4d7f-8cbe-d39940c5aaad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create_left_panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='create_left_panel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79eab7b8-fc9b-4f7a-ad8f-46f782955928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1yr1hnr</value>
      <webElementGuid>06ee639d-d4ab-4e90-9b06-68688db5da9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create_left_panel</value>
      <webElementGuid>ee5fe75b-6992-4ac3-8805-2b2d3a7c634d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>서명 참여자편집​서명날짜텍스트콤보 박스체크 박스라디오 버튼내 프로필첨부 파일​서명 순서 지정하기내 서명 문서로 만들기발송 전용 문서로 만들기</value>
      <webElementGuid>c7e17643-548c-4525-bc71-30d8bfe96fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_left_panel&quot;)</value>
      <webElementGuid>cb8fbfa0-fbd6-4515-8b16-230b60051d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']</value>
      <webElementGuid>130bf2b8-84ea-4336-b34a-7a1acb91cdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div[2]</value>
      <webElementGuid>cd8415bd-3a9e-410a-a2be-bde03991e60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='계속'])[1]/following::div[5]</value>
      <webElementGuid>971defaa-f1d6-4aee-931b-8b8669f1c698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::div[6]</value>
      <webElementGuid>a2f289be-e734-4702-888b-1dd2d68c83bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>66513bef-44e5-446d-a501-716ef0bbd363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'create_left_panel' and (text() = '서명 참여자편집​서명날짜텍스트콤보 박스체크 박스라디오 버튼내 프로필첨부 파일​서명 순서 지정하기내 서명 문서로 만들기발송 전용 문서로 만들기' or . = '서명 참여자편집​서명날짜텍스트콤보 박스체크 박스라디오 버튼내 프로필첨부 파일​서명 순서 지정하기내 서명 문서로 만들기발송 전용 문서로 만들기')]</value>
      <webElementGuid>d17d57cc-28f7-4be1-9453-7068f08c9072</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
