<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>단일 발송</name>
   <tag></tag>
   <elementGuidId>6fffb447-2c6c-4b0b-9472-59935ffb09c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-jtgvep</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 방식 또는 수신인에 맞춰 서명 문서의 발송 유형을 선택해요.'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4717b00-6a0c-4438-a208-4c9cfd9c6af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-jtgvep</value>
      <webElementGuid>2c515bf9-e13c-4138-9150-9fcab558e0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>단일 발송서명 문서를 한 명의 수신자에게 발송해요</value>
      <webElementGuid>ef74a9dc-e0cf-426f-9406-b16119e9d639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fonts-loaded&quot;]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root css-xym8ww&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthFalse css-lne1r5&quot;]/div[@class=&quot;MuiDialogContent-root css-1cqplmn&quot;]/div[@class=&quot;MuiBox-root css-1d97gup&quot;]/div[@class=&quot;MuiBox-root css-jtgvep&quot;]</value>
      <webElementGuid>ca965d38-6483-4f19-84d1-343d16c443a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10000</value>
      <webElementGuid>530ad386-0404-400b-a5ab-0e46eca35244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 방식 또는 수신인에 맞춰 서명 문서의 발송 유형을 선택해요.'])[1]/following::div[1]</value>
      <webElementGuid>f4e752b6-a877-4b76-bd41-fe3efef4b96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='발송 유형 선택'])[1]/following::div[5]</value>
      <webElementGuid>ce0f562f-7a62-41a0-a90c-cd106e95b035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]</value>
      <webElementGuid>02d22e4d-ee6a-4478-9dae-63cc19c4b877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '단일 발송서명 문서를 한 명의 수신자에게 발송해요' or . = '단일 발송서명 문서를 한 명의 수신자에게 발송해요')]</value>
      <webElementGuid>0a480322-1004-468e-b68e-1a2de254ccca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>394f223c-72a0-42c3-ac22-dbd17fe7d45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '​​참여자의 서명 필드가 없어요. 참여자를 제거하거나 필드를 추가해 주세요.서명 권한 양도서명 거부' or . = '​​참여자의 서명 필드가 없어요. 참여자를 제거하거나 필드를 추가해 주세요.서명 권한 양도서명 거부')]</value>
      <webElementGuid>23639e5d-b78f-4996-91eb-927bae7aa861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]</value>
      <webElementGuid>2f9e3cbf-428f-436d-b6b2-fb6fc40f03ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>cf67d9f5-023a-42f9-bd1e-e42377f23101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '취소편집 완료' or . = '취소편집 완료')]</value>
      <webElementGuid>c76f7c96-6c39-4edd-8673-1d299abb5f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
