<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>두번째 사용자 선택</name>
   <tag></tag>
   <elementGuidId>0928eecb-8481-4b66-a8ab-5575a5529e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-13tadqh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='create_left_panel']/div[2]/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b28f62e1-08c1-4e21-bc62-05540a4f2900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-13tadqh</value>
      <webElementGuid>6e559f5d-39a6-48d6-a834-32d0cb3b01a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10000</value>
      <webElementGuid>15c9c336-567a-4e7a-8fa8-e50ab68d4331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>83611d9d-52c3-4c17-89b4-7734ddc5a9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_left_panel&quot;)/div[@class=&quot;MuiBox-root css-2nu0oh&quot;]/div[@class=&quot;styled__Wrapper-sc-dsfye4-0 fIONZu&quot;]/div[@class=&quot;MuiBox-root css-13tadqh&quot;]</value>
      <webElementGuid>eaf91a6a-49fa-4dfd-8f04-fb8499eb2dac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div[2]/div[3]</value>
      <webElementGuid>0bfea355-805c-419b-980b-93b608cef8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::div[21]</value>
      <webElementGuid>56f40632-7bdc-4a5b-b489-49b85f60dec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='편집'])[1]/following::div[29]</value>
      <webElementGuid>2f082e6d-d9a3-410b-a9b3-4f5c7fd52c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[4]/preceding::div[11]</value>
      <webElementGuid>a00388d9-daa8-4901-abe2-dbdcc52fc95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[3]</value>
      <webElementGuid>0e91caff-dd00-47bf-8bfb-2624e3c296d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '​' or . = '​')]</value>
      <webElementGuid>f800371e-ee80-470c-885c-6b1a29ccf6ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
