<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>문서발송 체크</name>
   <tag></tag>
   <elementGuidId>cf9f66c7-25d8-48bb-b2b4-c372ff32fc58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-15r9tjl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f766f1fd-1673-4098-874e-b1a9db92ba88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-15r9tjl</value>
      <webElementGuid>0235591f-6e96-45bf-ac5a-1835752f5eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sample_pdf</value>
      <webElementGuid>717baf93-e488-4a8b-adb8-da60f93e06d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-3vsr9p&quot;]/div[@class=&quot;MuiBox-root css-1ik4laa&quot;]/div[@class=&quot;MuiBox-root css-hpuc4i&quot;]/main[@class=&quot;MuiBox-root css-roxj3j&quot;]/div[@class=&quot;MuiBox-root css-11jivkb&quot;]/div[@class=&quot;MuiBox-root css-1yygsgg&quot;]/div[@class=&quot;MuiBox-root css-1ofqig9&quot;]/div[@class=&quot;MuiBox-root css-1alisiy&quot;]/div[@class=&quot;MuiBox-root css-jd9oio&quot;]/div[@class=&quot;MuiBox-root css-f2p51g&quot;]/div[@class=&quot;MuiBox-root css-tb1ehf&quot;]/div[@class=&quot;MuiBox-root css-omv5r1&quot;]/div[@class=&quot;MuiBox-root css-15r9tjl&quot;]</value>
      <webElementGuid>2d2277a8-0fce-44a3-8e21-d4736b622bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[2]/div/div/div/div</value>
      <webElementGuid>14898756-db51-4b79-88f7-93ed216f1a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='진행 중'])[2]/following::div[5]</value>
      <webElementGuid>fb37738c-62ee-4419-aefc-6ed0419b92c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='관리'])[1]/following::div[9]</value>
      <webElementGuid>04237bf5-fa30-4816-98f7-ab0fbb8ba4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 요청자:'])[1]/preceding::div[1]</value>
      <webElementGuid>75c2df1b-1dda-4264-a258-bac3a94e12d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sample_pdf']/parent::*</value>
      <webElementGuid>af197f75-6269-4860-a17b-4f2215dd5a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div</value>
      <webElementGuid>b95d8a0e-419e-4ff5-a97a-b4e140ef3f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'sample_pdf' or . = 'sample_pdf')]</value>
      <webElementGuid>9a162353-60be-4ecd-8374-9197fb3a55c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[3]/div/div/div/div</value>
      <webElementGuid>da1a419e-14c8-4f69-b7ca-dd77d8e12480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='완료'])[1]/following::div[5]</value>
      <webElementGuid>eff4d507-460d-449f-ad94-72a6dfe7ca04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='관리'])[1]/following::div[10]</value>
      <webElementGuid>a6234282-b5df-440b-a3f2-605ebf65ae45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div</value>
      <webElementGuid>be5fb68c-edb0-4265-982d-11a5f41e01ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='거부'])[1]/following::div[5]</value>
      <webElementGuid>b9c7fc11-3c79-426d-8537-ee98295e01d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>3b884c09-f0f8-41ee-a6a0-f01838534aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='관리'])[1]/following::div[7]</value>
      <webElementGuid>bb97c64a-0205-4e1c-b65d-d9f2d7dcdc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='만료일'])[1]/following::div[8]</value>
      <webElementGuid>14835d65-7237-40ae-8417-d71ad450ef14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 요청자:'])[1]/preceding::div[7]</value>
      <webElementGuid>22322204-2b8c-43b5-9391-f6b949a79dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>fbe3ac4e-28b5-4098-bdc4-b5257da41abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='진행 중'])[1]/following::div[5]</value>
      <webElementGuid>30837079-debb-4234-a71e-927895f383bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
