<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>문서발송 체크</name>
   <tag></tag>
   <elementGuidId>cf9f66c7-25d8-48bb-b2b4-c372ff32fc58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-15r9tjl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0235aaf9-cc0c-4ed1-9a2f-449501945f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-15r9tjl</value>
      <webElementGuid>0c24d7b9-1dc1-49ab-b73f-ee81d686ff65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sample_pdf</value>
      <webElementGuid>2e5ecb65-2259-4ae7-935d-5df968e22cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-3vsr9p&quot;]/div[@class=&quot;MuiBox-root css-1ik4laa&quot;]/div[@class=&quot;MuiBox-root css-hpuc4i&quot;]/main[@class=&quot;MuiBox-root css-roxj3j&quot;]/div[@class=&quot;MuiBox-root css-11jivkb&quot;]/div[@class=&quot;MuiBox-root css-1yygsgg&quot;]/div[@class=&quot;MuiBox-root css-1ofqig9&quot;]/div[@class=&quot;MuiBox-root css-1alisiy&quot;]/div[@class=&quot;MuiBox-root css-jd9oio&quot;]/div[@class=&quot;MuiBox-root css-f2p51g&quot;]/div[@class=&quot;MuiBox-root css-tb1ehf&quot;]/div[@class=&quot;MuiBox-root css-omv5r1&quot;]/div[@class=&quot;MuiBox-root css-15r9tjl&quot;]</value>
      <webElementGuid>b9518e4d-a4b5-4e2b-b8b3-1a1d2092c6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[2]/div/div/div/div</value>
      <webElementGuid>aa9d62c8-b052-4a95-a299-d7f42be92d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='진행 중'])[2]/following::div[5]</value>
      <webElementGuid>ba5fed8b-d0d0-4782-996c-79c66cf79ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='관리'])[1]/following::div[9]</value>
      <webElementGuid>0a77a24a-435a-402f-89dd-7321690e2e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 요청자:'])[1]/preceding::div[1]</value>
      <webElementGuid>f3ff3eaf-23fb-4a02-884f-ac4bc601eef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sample_pdf']/parent::*</value>
      <webElementGuid>0866207c-9909-41d8-a2a8-25ba4aef09e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div</value>
      <webElementGuid>2fa20aa2-a20c-4220-94c9-508a9b77620e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'sample_pdf' or . = 'sample_pdf')]</value>
      <webElementGuid>dd428f99-eb40-4c4d-84fb-14e502bea7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[3]/div/div/div/div</value>
      <webElementGuid>ce933b76-f717-41b7-b5e4-c0b6a661beb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='완료'])[1]/following::div[5]</value>
      <webElementGuid>59c3cd9b-61b9-43b2-b4cb-267cb9c16f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='관리'])[1]/following::div[10]</value>
      <webElementGuid>e46b8971-17f1-44c1-8243-ac198defe5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div</value>
      <webElementGuid>02f5ccaa-4886-43ff-9c44-32ce635edb58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='거부'])[1]/following::div[5]</value>
      <webElementGuid>afd29c4d-07ea-45f3-94cf-52fcd9843200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>1004a82a-2b32-4b66-9b6e-38e537e1cc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='관리'])[1]/following::div[7]</value>
      <webElementGuid>0c7cb001-cd72-488c-9abc-985452d42959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='만료일'])[1]/following::div[8]</value>
      <webElementGuid>dc34513f-962a-45af-b3c2-32f1fa1096f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 요청자:'])[1]/preceding::div[7]</value>
      <webElementGuid>cef3a361-0316-4242-93c8-fdcab72dd749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>baced234-cb30-4332-a06c-8bcc6c78cf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='진행 중'])[1]/following::div[5]</value>
      <webElementGuid>02532a79-9e0d-48dd-8a9b-7a9e2e66a485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
