<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명양도_보내기 버튼</name>
   <tag></tag>
   <elementGuidId>3870b945-8d2f-4385-aae1-681d3bb55e5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReviewSend-Send-GetSignatures</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ReviewSend-Send-GetSignatures']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98493046-c762-404c-a660-553ecc2e3c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-color MuiButton-colorPrimary MuiButton-sizeMedium MuiButton-colorSizeMedium MuiButton-root MuiButton-color MuiButton-colorPrimary MuiButton-sizeMedium MuiButton-colorSizeMedium css-14i31n7</value>
      <webElementGuid>c0c50187-d8c1-477a-87dc-7da4f94a69ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>112f8580-2b62-49a7-96c4-ca3a446d2661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60542691-16ed-430c-940e-584c3ed936a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReviewSend-Send-GetSignatures</value>
      <webElementGuid>26a79dfe-143e-4872-a2e5-34e5fd937001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>보내기</value>
      <webElementGuid>685bf704-9ce7-4bfb-af33-0e677308b86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReviewSend-Send-GetSignatures&quot;)</value>
      <webElementGuid>7cc61b07-6562-4d4d-86b5-06fc5c103a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ReviewSend-Send-GetSignatures']</value>
      <webElementGuid>de3d8d13-4d95-4bea-ad35-114dbf7f2c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='임시 저장'])[1]/following::button[1]</value>
      <webElementGuid>21c75066-acb1-4c63-bd6a-d18acc224e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[10]/following::button[4]</value>
      <webElementGuid>3c4b4022-ef5e-47d3-8097-3a14be173775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='보내기']/parent::*</value>
      <webElementGuid>692f7c35-7fa8-44ca-af1d-e195835ec6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>71029383-e8a1-4ac3-998b-44b97c42c5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'ReviewSend-Send-GetSignatures' and (text() = '보내기' or . = '보내기')]</value>
      <webElementGuid>b82bafba-fdc8-41e5-b3c6-6d8c789e6a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
