<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명순서 지정하기</name>
   <tag></tag>
   <elementGuidId>4e0020b5-b937-4e80-ab99-241cb158af4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styled__Input-sc-otvfr5-1.gywLlB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c98f673-ee72-44c2-879e-81b5e0b147ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Input-sc-otvfr5-1 gywLlB</value>
      <webElementGuid>1c25bc3d-9e3a-43f4-bc45-e24b03428768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d378d24d-ce76-4838-a158-a9879aae99ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ca1da33-36e1-4cf7-9691-353867a8b660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JackRabbit_d67dc191-7314-11ee-a609-cf758c16fcdf&quot;)/div[@class=&quot;styled__Wrapper-sc-lip6vl-0 jzzTRw&quot;]/div[@class=&quot;styled__Wrapper-sc-otvfr5-0 eYdKpa&quot;]/input[@class=&quot;styled__Input-sc-otvfr5-1 gywLlB&quot;]</value>
      <webElementGuid>c649766f-fc03-485c-a4be-021f7ac235e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>58b62e7b-e840-4285-9e78-b06a236fcc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JackRabbit_d67dc191-7314-11ee-a609-cf758c16fcdf']/div[2]/div/input</value>
      <webElementGuid>e0261afb-4a8b-4da9-9c48-f66750ccb14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>1492b08f-3606-4905-ad22-178a68949366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JackRabbit_3ace5e41-7313-11ee-b41f-a3ff9e06e683']/div[2]/div/input</value>
      <webElementGuid>06b7db0f-1cc7-4e68-8606-f63137a65cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JackRabbit_50429351-7312-11ee-a879-45bfde3dc427']/div[2]/div/input</value>
      <webElementGuid>6bbf48bf-ef34-4fba-a308-4b65e38d86d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JackRabbit_9a4fbcd0-6c04-11ee-8dc4-316c9a5ffd76']/div[2]/div/input</value>
      <webElementGuid>29d3a38c-5d18-40f5-944e-4a26cbdf5565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>3714239f-2707-45a4-8938-89199eba7402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JackRabbit_aba6ac00-6c04-11ee-8dc4-316c9a5ffd76']/div[2]/div/input</value>
      <webElementGuid>966df993-fc1d-4bf5-a802-cef23ffb797b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>79c72bc6-8f33-4364-91bc-dbc3e6a58956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[8]</value>
      <webElementGuid>fa686fda-6a59-4551-b9a0-ef0a2a9837dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/label/span/input</value>
      <webElementGuid>ba57894e-d4af-4326-b87d-9feb9d879b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>97de85d8-0932-4f16-8c9c-75cae0529116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[3]</value>
      <webElementGuid>f46bb48a-3d5e-4d22-8f35-ccca75e2297b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div[4]/label/span/input</value>
      <webElementGuid>6d6cdf66-c2ad-4693-98b7-b4abf4e03c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/span/input</value>
      <webElementGuid>d31a4e36-5f6c-4ee7-962b-a156eabf53f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>28fa0d03-79ab-46ac-a859-33d6b80381fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='Edit-SignerOrder-GetSignatures']/span/input</value>
      <webElementGuid>e5f57dc3-b219-4110-bd2b-252fba82c924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span/input</value>
      <webElementGuid>6c009233-2e92-43ac-a365-101dd8ef297b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
