<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명거부_로그인버튼</name>
   <tag></tag>
   <elementGuidId>9bfc79dc-b847-4f7a-aef4-615888b6efe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hancomsign_login > a.button--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hancomsign_login']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>791b84c4-924a-4250-85cc-418d5724cb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://my.stg.hancomsign.com/login.html</value>
      <webElementGuid>8048abb1-b681-4c2f-a206-a5a45c7c1e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button--primary</value>
      <webElementGuid>ba74887e-da41-404c-bcae-ab519d1362e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>3952f393-8b11-4653-aad2-3995a6dee9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그인</value>
      <webElementGuid>8b102313-5e0b-4dc5-bfe4-285ed38801af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hancomsign_login&quot;)/a[@class=&quot;button--primary&quot;]</value>
      <webElementGuid>bf469e20-8c43-4150-861c-cc1e0efeffd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hancomsign_login']/a</value>
      <webElementGuid>74a1c0a6-3473-4f04-9273-f336d3ae6d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'로그인')]</value>
      <webElementGuid>1a1216a5-bac2-4589-9065-867cb0090b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='시작하기'])[1]/following::a[1]</value>
      <webElementGuid>ab9db92c-4087-4ead-87e9-0480d7cbae94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='로그아웃'])[1]/following::a[2]</value>
      <webElementGuid>f1be060d-ec4a-4642-ae90-2e1cbe9eea76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'hancomsign_login', '&quot;', ')/a[@class=', '&quot;', 'button--primary', '&quot;', ']')])[1]/preceding::a[1]</value>
      <webElementGuid>d1f66524-6d75-4d7a-8250-65654c9c8ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='로그인']/parent::*</value>
      <webElementGuid>489443de-4f57-43ea-a2ca-da85496e8279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://my.stg.hancomsign.com/login.html')]</value>
      <webElementGuid>e08d72e3-2340-4f86-a8b7-416d527c2f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>1d1da012-733a-44a6-a300-61abaf4593d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://my.stg.hancomsign.com/login.html' and (text() = '로그인' or . = '로그인')]</value>
      <webElementGuid>3a05d971-a5d4-455d-8e91-de111d5691cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
