<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명거부_편집버튼</name>
   <tag></tag>
   <elementGuidId>633ca3ac-1ba9-4d76-93f6-5b0b2c93efc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Assign-Fields-Edit-GetSignatures</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e4d54a0-39ee-408d-9840-1b549d5402dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assign-Fields-Edit-GetSignatures</value>
      <webElementGuid>e25a2719-1b32-4615-8624-11d58b485677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styledCreate__BtnEdit-sc-1e5ee0j-3 eFbBUR</value>
      <webElementGuid>aeccf690-6052-4fb9-b01f-5bd629fff7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>편집</value>
      <webElementGuid>0cea2c7a-bbe0-4adc-bc3a-19ee5fc895aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assign-Fields-Edit-GetSignatures&quot;)</value>
      <webElementGuid>280e3187-3fba-41ca-83b5-72ea39868071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      <webElementGuid>758831e3-eba1-4b18-9219-27af1d2697ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div/div</value>
      <webElementGuid>3c83f9f9-7d5b-4089-9e73-d415bfb1301d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='계속'])[1]/following::div[10]</value>
      <webElementGuid>d82359c3-0efb-40df-94f1-10c5ea2bf12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::div[3]</value>
      <webElementGuid>4b63ae8f-090d-422b-8281-d12cfd2ec036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/preceding::div[31]</value>
      <webElementGuid>f553ae72-2c32-425a-b44f-a4ffb088b956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='편집']/parent::*</value>
      <webElementGuid>348e1f21-2e47-4664-9843-0f7515d2f986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div</value>
      <webElementGuid>66cca9b9-434c-458d-b850-f3b6233181f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Assign-Fields-Edit-GetSignatures' and (text() = '편집' or . = '편집')]</value>
      <webElementGuid>80f08107-84a8-4ec1-90c0-0c86cadab466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
