<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명양도_ STG004 프로필 영역</name>
   <tag></tag>
   <elementGuidId>5afe5d7e-37ba-4d1c-acbf-4de01c41b3b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85237d7c-be9b-459a-9589-10be045a50e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1kgeuuc</value>
      <webElementGuid>d0f54a11-8b97-4c8b-b14b-3882f9990158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-box</value>
      <webElementGuid>6b7b9f29-3d63-46cf-88c3-8c0c4efaed40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3209f5cc-de5a-4ed1-b363-305e45c26492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>서비스품질팀 STG자동화004signtest004@tech-mail.net</value>
      <webElementGuid>173fab25-2292-419f-8d15-4a054519d2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-box&quot;)</value>
      <webElementGuid>6b8f5575-c0c1-4408-88a9-6d534d65cc27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='user-box']</value>
      <webElementGuid>68d16635-cc1a-415b-aaaf-202c1d908c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>6ef13f9d-a7ba-47f7-8abc-4debd4cb8966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='시작하기'])[1]/preceding::div[9]</value>
      <webElementGuid>85462968-4197-4dae-b7fa-ea30ab50d54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>d71ec408-1dd5-4cd1-b5c8-1b559627263f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'user-box' and (text() = '서비스품질팀 STG자동화004signtest004@tech-mail.net' or . = '서비스품질팀 STG자동화004signtest004@tech-mail.net')]</value>
      <webElementGuid>d0979cb5-1323-4522-b317-b3db24868fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
