<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명양도_PDF캔버스</name>
   <tag></tag>
   <elementGuidId>fa1dc7c7-d778-416e-bb99-e6cd38737436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.react-pdf__Page__canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageContainer1']/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>37d74959-03fe-4ce7-a95b-15d50c1ec779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-pdf__Page__canvas</value>
      <webElementGuid>a5486143-c152-4d66-b997-da39f8fe5fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1606</value>
      <webElementGuid>31fc9044-3091-49a8-a1c2-290715f4cb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2270</value>
      <webElementGuid>95a3a4d5-a419-4e7a-85e4-8687a65a62f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContainer1&quot;)/div[@class=&quot;react-pdf__Page&quot;]/canvas[@class=&quot;react-pdf__Page__canvas&quot;]</value>
      <webElementGuid>8824c7e0-badb-44d7-aa70-bce4a0c86d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageContainer1']/div/canvas</value>
      <webElementGuid>1c9a4294-d977-4b15-8289-03bcb7c03c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>2b68b49e-233b-4f71-ab6a-8bc4918474b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
