<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명거부_프로필</name>
   <tag></tag>
   <elementGuidId>684bd952-76ad-4908-896b-172129e9e500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1xoz5k8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-box']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>599a5830-0fb8-4565-b694-4848cb10f3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.stg.hancomsign.com/20220629/v1/images/avatar/avatar_00.png</value>
      <webElementGuid>4df535da-9a05-4872-ab21-35104574f7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xoz5k8</value>
      <webElementGuid>14878447-74e9-4d17-8c65-3ea7d3cfd7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-box&quot;)/div[@class=&quot;css-1n0zp4h&quot;]/div[@class=&quot;css-1xoz5k8&quot;]</value>
      <webElementGuid>71615d4a-bdc1-4a73-8226-b84915e80d06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-box']/div/div</value>
      <webElementGuid>ef9cda13-47eb-4ab8-97be-58dadd24101a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>880a5da2-7d21-4a5a-a39b-5c505a9154b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@src = 'https://static.stg.hancomsign.com/20220629/v1/images/avatar/avatar_00.png']</value>
      <webElementGuid>1e84a246-142e-4684-985d-0bf70b7824f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
