<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명양도_STG005프로필</name>
   <tag></tag>
   <elementGuidId>928f21eb-e0ae-4214-a2e0-ea6ce8651f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f96cd575-4895-4665-a5bd-80f848fa620b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1kgeuuc</value>
      <webElementGuid>82c1c4f0-2274-4d7e-bb5e-683f171501f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-box</value>
      <webElementGuid>b74c3050-c979-4c36-ae2f-86c1f27f2c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0b3d028-60da-49cb-aa3a-12fd12dcc242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>서비스품질팀 STG자동화005signtest005@tech-mail.net</value>
      <webElementGuid>78b8661a-1132-4302-a79f-9f91e571d82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-box&quot;)</value>
      <webElementGuid>f36caf3a-cf45-45ea-a4bf-55c8e55dee3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='user-box']</value>
      <webElementGuid>14193469-5054-4132-9fbc-1176ed7b0261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>41e4295f-c849-47ef-960b-559032b64ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='시작하기'])[1]/preceding::div[9]</value>
      <webElementGuid>d21d727a-c7f3-4d28-a9f6-ece6ee83a3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>74278b61-6a51-47b5-bfec-6d6123e3638c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'user-box' and (text() = '서비스품질팀 STG자동화005signtest005@tech-mail.net' or . = '서비스품질팀 STG자동화005signtest005@tech-mail.net')]</value>
      <webElementGuid>10749b88-6811-4899-9edf-e246da1ff533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
