<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명양도_편집버튼</name>
   <tag></tag>
   <elementGuidId>bf12a0c6-2692-4e1b-95aa-f9ddcf397558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Assign-Fields-Edit-GetSignatures</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6f4921f-841b-46f8-ac0d-12187c385f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assign-Fields-Edit-GetSignatures</value>
      <webElementGuid>be5beceb-6bd1-42d1-97d8-6fbc181e27b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styledCreate__BtnEdit-sc-1e5ee0j-3 eFbBUR</value>
      <webElementGuid>7b4b58a0-9c4d-4008-8131-1cc00b98ec1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>편집</value>
      <webElementGuid>b0a1df38-57ba-4442-a88c-58dc4c6bae23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assign-Fields-Edit-GetSignatures&quot;)</value>
      <webElementGuid>f4d5435b-95d4-45f3-a41f-1b59d16f327b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      <webElementGuid>15e99232-4d86-4f70-bcd0-315a2db5f51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div/div</value>
      <webElementGuid>0b1d330f-bad7-498e-aed8-b735b5a009a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='계속'])[1]/following::div[10]</value>
      <webElementGuid>55fa40bd-bc8f-4007-9c03-936d76eec135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::div[3]</value>
      <webElementGuid>37b2b6e7-e1d7-4e83-be29-55c78ec3d604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/preceding::div[31]</value>
      <webElementGuid>1d83f74d-f4b4-4c85-afb6-9fb9305f0252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='편집']/parent::*</value>
      <webElementGuid>1aed8b9c-5761-4cf1-b626-0c76a3c6b939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div</value>
      <webElementGuid>87c8b3bb-75a2-4ce4-a7d0-70dfb4e986d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Assign-Fields-Edit-GetSignatures' and (text() = '편집' or . = '편집')]</value>
      <webElementGuid>8724baaa-6477-4629-abc8-4648d232c4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
