<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명문서없음 체크포인트</name>
   <tag></tag>
   <elementGuidId>07620529-13c2-4bf9-a8d6-e40b84dd552d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.styled__Sketch-sc-p8azkf-1.jwXGqK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c984647-3102-4b86-b0a0-c05e48667b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.stg.hancomsign.com/20230330/v1/images/blank/taskList.svg</value>
      <webElementGuid>9f62743a-a7ec-497f-a650-078fdef64167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sketch</value>
      <webElementGuid>b0f9d8b2-d9b8-46df-8dab-877469f6987e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Sketch-sc-p8azkf-1 jwXGqK</value>
      <webElementGuid>74840041-a785-4920-9ef4-1384a8cfe7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-3vsr9p&quot;]/div[@class=&quot;MuiBox-root css-1ik4laa&quot;]/div[@class=&quot;MuiBox-root css-hpuc4i&quot;]/main[@class=&quot;MuiBox-root css-roxj3j&quot;]/div[@class=&quot;MuiBox-root css-11jivkb&quot;]/div[@class=&quot;MuiBox-root css-1yygsgg&quot;]/div[@class=&quot;MuiBox-root css-1ofqig9&quot;]/div[@class=&quot;styled__Wrapper-sc-p8azkf-0 gdaqHR&quot;]/img[@class=&quot;styled__Sketch-sc-p8azkf-1 jwXGqK&quot;]</value>
      <webElementGuid>49ea10ed-6d8a-40ed-a41a-d59fdd17cad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[2]/img</value>
      <webElementGuid>ad6975b1-c1fc-4f84-8a74-afae985a81b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='sketch']</value>
      <webElementGuid>bcd92422-3028-43ec-aabc-682b413d32f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>736a0316-e1d9-47ad-b234-92d56ff210d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.stg.hancomsign.com/20230330/v1/images/blank/taskList.svg' and @alt = 'sketch']</value>
      <webElementGuid>e10c79e8-1041-4f99-b7c5-22c7e1822233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
