<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명거부_서명문서없음체크</name>
   <tag></tag>
   <elementGuidId>3c1055ba-5bd6-46ad-a434-4450e304c875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.styled__Sketch-sc-p8azkf-1.jwXGqK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a7e25d6b-4a3a-491f-a005-bd2f7d13fab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.stg.hancomsign.com/20230330/v1/images/blank/taskList.svg</value>
      <webElementGuid>b30297bb-fe9b-4c94-ad66-0468954e9e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sketch</value>
      <webElementGuid>e8ebce66-95ca-45e5-b1fd-575ced53fcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Sketch-sc-p8azkf-1 jwXGqK</value>
      <webElementGuid>8e4e62df-8f83-4b3b-8d8f-4bed87aa234b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-3vsr9p&quot;]/div[@class=&quot;MuiBox-root css-1ik4laa&quot;]/div[@class=&quot;MuiBox-root css-hpuc4i&quot;]/main[@class=&quot;MuiBox-root css-roxj3j&quot;]/div[@class=&quot;MuiBox-root css-11jivkb&quot;]/div[@class=&quot;MuiBox-root css-1yygsgg&quot;]/div[@class=&quot;MuiBox-root css-1ofqig9&quot;]/div[@class=&quot;styled__Wrapper-sc-p8azkf-0 gdaqHR&quot;]/img[@class=&quot;styled__Sketch-sc-p8azkf-1 jwXGqK&quot;]</value>
      <webElementGuid>0d7a5e4f-3345-45aa-b00a-75a96c856ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[2]/img</value>
      <webElementGuid>9af48e31-66b8-4dfa-9e39-2e695ff2cee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='sketch']</value>
      <webElementGuid>9d72a93f-5ed9-4065-870f-05c6c3f5f113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>4ba4c239-5f99-4f02-9b4e-014d4cfe5af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.stg.hancomsign.com/20230330/v1/images/blank/taskList.svg' and @alt = 'sketch']</value>
      <webElementGuid>45913945-3083-4c71-b853-1a36e778d779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
