<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명순서 지정하기</name>
   <tag></tag>
   <elementGuidId>4e0020b5-b937-4e80-ab99-241cb158af4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styled__Input-sc-otvfr5-1.gywLlB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>104e73bb-4417-457d-92a2-259989278c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Input-sc-otvfr5-1 gywLlB</value>
      <webElementGuid>81eef1ee-ba66-41b7-adae-d087f0e95dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a6bf380b-c4fb-49e0-b993-56897117668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c5b6221-4d95-42ea-8685-4ba12d4c0b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JackRabbit_9a4fbcd0-6c04-11ee-8dc4-316c9a5ffd76&quot;)/div[@class=&quot;styled__Wrapper-sc-lip6vl-0 jzzTRw&quot;]/div[@class=&quot;styled__Wrapper-sc-otvfr5-0 eYdKpa&quot;]/input[@class=&quot;styled__Input-sc-otvfr5-1 gywLlB&quot;]</value>
      <webElementGuid>c524b539-942d-4e02-98dd-0e349e86d474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>8c265edc-9b57-47cc-a40a-47768bcad54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JackRabbit_9a4fbcd0-6c04-11ee-8dc4-316c9a5ffd76']/div[2]/div/input</value>
      <webElementGuid>950e538a-11d4-46d5-9b07-4aa40e03f2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>8199e9d2-bbfd-4f4b-b10a-bb9aebcb26d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>fe9a7cd2-00f7-4cc5-ab3c-938a5020a37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JackRabbit_aba6ac00-6c04-11ee-8dc4-316c9a5ffd76']/div[2]/div/input</value>
      <webElementGuid>4f1b56fb-76cf-4581-bae6-9c26453e23d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>b3e36d75-5a37-4cc9-b813-a0e20db519b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[8]</value>
      <webElementGuid>184835b6-28fd-4e3d-9c28-fea59e81bd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/label/span/input</value>
      <webElementGuid>2b17e222-fba5-4312-8b84-bb86fc5632e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>a2d8fb64-647b-40b6-9dca-be3c7e34dae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[3]</value>
      <webElementGuid>0577aa27-f4b1-4aac-8892-4ce9562f4a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div[4]/label/span/input</value>
      <webElementGuid>97958cf2-3955-4702-a975-c5529fc7b6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/span/input</value>
      <webElementGuid>82c37f5e-9909-4226-8aa7-677c8a2b5acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>1a065681-1d94-4775-aae3-9d431e3cf70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='Edit-SignerOrder-GetSignatures']/span/input</value>
      <webElementGuid>51c2ebd1-d72f-445e-99c0-845fc2db89ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span/input</value>
      <webElementGuid>357b918d-bb7a-451e-aa2d-3c35d17a61b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
