<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>시작하기</name>
   <tag></tag>
   <elementGuidId>eef66474-c890-4279-a15e-1da7b194c511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.MuiButton-root.MuiButton-fill.MuiButton-fillPrimary.MuiButton-sizeXlarge.MuiButton-fillSizeXlarge.MuiButton-fullWidth.MuiButton-root.MuiButton-fill.MuiButton-fillPrimary.MuiButton-sizeXlarge.MuiButton-fillSizeXlarge.MuiButton-fullWidth.css-skbmlx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2310db59-401c-48f3-b30f-9655d20215e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-fill MuiButton-fillPrimary MuiButton-sizeXlarge MuiButton-fillSizeXlarge MuiButton-fullWidth MuiButton-root MuiButton-fill MuiButton-fillPrimary MuiButton-sizeXlarge MuiButton-fillSizeXlarge MuiButton-fullWidth css-skbmlx</value>
      <webElementGuid>6f8d32af-dbf7-41b6-a55e-34e61bfd096f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fc11a3e0-d6c9-4720-ba60-c5199a67d674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>038b2af1-7eda-4322-a04a-6d71482954aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>backgroundcolor</name>
      <type>Main</type>
      <value>var(--main)</value>
      <webElementGuid>5dd3b452-f295-4497-a08e-7fb94740ac96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>시작하기</value>
      <webElementGuid>f894ebb3-bc12-4ba8-8a4c-395bedf53d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-3vsr9p&quot;]/div[@class=&quot;MuiBox-root css-1ik4laa&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked css-sr7x0k&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft css-mqusjk&quot;]/div[@class=&quot;MuiBox-root css-ulowph&quot;]/ul[@class=&quot;MuiList-root MuiList-padding css-1wobn4j&quot;]/div[@class=&quot;MuiBox-root css-1kiwrpv&quot;]/div[@class=&quot;MuiBox-root css-8atqhb&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-fill MuiButton-fillPrimary MuiButton-sizeXlarge MuiButton-fillSizeXlarge MuiButton-fullWidth MuiButton-root MuiButton-fill MuiButton-fillPrimary MuiButton-sizeXlarge MuiButton-fillSizeXlarge MuiButton-fullWidth css-skbmlx&quot;]</value>
      <webElementGuid>06c344e5-1152-4784-a84a-03ca8ef678cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>d87854ba-58eb-4f73-901f-5ee69582834d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/ul/div/div/button</value>
      <webElementGuid>ca8274d6-339a-4ad8-a53b-13e3abf902b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서비스품질팀 STG자동화001'])[1]/following::button[1]</value>
      <webElementGuid>6122684e-a092-4833-aa73-e53ce025afe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='받은 문서'])[1]/preceding::button[1]</value>
      <webElementGuid>b7d7818c-48d3-4cc7-a359-0c45d1fb8120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='문서함'])[1]/preceding::button[1]</value>
      <webElementGuid>c358de3a-02a8-4ca5-bab2-393cb8b945ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='시작하기']/parent::*</value>
      <webElementGuid>7ee76111-6f53-4736-a5c0-028d7e6aa7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/button</value>
      <webElementGuid>167afe84-1e6d-4016-a32c-2cf74a98b9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '시작하기' or . = '시작하기')]</value>
      <webElementGuid>9acae184-5fd6-41ee-8f52-e2225964db7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
