<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>웹오피스 프레임</name>
   <tag></tag>
   <elementGuidId>0c4873d7-7e1d-449e-8fa0-e113ff15325b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create_task_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='create_task_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6db98395-b0c8-4905-8417-38e38432d21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TitleBarCreate__StyleBox-sc-1auz653-0 gmqgzV MuiBox-root css-0</value>
      <webElementGuid>7daf514c-94bf-477a-8378-228b8d830364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create_task_title</value>
      <webElementGuid>cff85a95-7ab7-4ff0-88c9-aae060bbd66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sample_docx</value>
      <webElementGuid>b607f18a-7034-4356-b437-e576052d5b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_task_title&quot;)</value>
      <webElementGuid>077d3821-7c68-4602-8281-44b194df726a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='create_task_title']</value>
      <webElementGuid>048cdcdd-324d-4b23-84be-0985f752c557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>e2cc9b82-953c-4fc0-b9ac-eb91f1f9c2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/preceding::div[6]</value>
      <webElementGuid>a9110f20-023f-4949-8ab0-efae842bb38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='편집 완료'])[1]/preceding::div[7]</value>
      <webElementGuid>ffc19335-33b8-4bd7-8f62-c369c5ee5984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>b7f534d3-0e0b-42bc-ada9-0080ba32249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'create_task_title' and (text() = 'sample_docx' or . = 'sample_docx')]</value>
      <webElementGuid>b1cd772a-c8fb-4042-94a8-c1d84dea6ee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
