<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>웹오피스 하단프레임</name>
   <tag></tag>
   <elementGuidId>79b5b304-59e2-419f-ae23-d0f228478e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styled__Wrapper-sc-273jui-0.fbRZiS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd361750-a5ba-428e-acc9-8fd8f5abe0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Wrapper-sc-273jui-0 fbRZiS</value>
      <webElementGuid>27625f9e-3d37-4b77-a51b-ffe408def6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>970f9510-cb6a-4d23-bac2-d222b99e0f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell-0-서명자1-이메일</value>
      <webElementGuid>2b2fdf92-70fb-4568-8f7d-1753f20b2b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>취소편집 완료</value>
      <webElementGuid>a8236ead-bb15-4e34-8084-6fd1f071c7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-4qljru&quot;]/div[@class=&quot;styled__Wrapper-sc-273jui-0 fbRZiS&quot;]</value>
      <webElementGuid>77a7316a-b508-4e5f-8e85-0f06932bb9d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]</value>
      <webElementGuid>2b0860a1-c739-421c-83ae-b8e7fdfc6e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>4c2467fc-5a4a-476f-8d5b-5751a72a7efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '취소편집 완료' or . = '취소편집 완료')]</value>
      <webElementGuid>ec353c85-cd50-4100-9db7-4e25b41f3960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cell-0-서명자1-이메일']</value>
      <webElementGuid>34060fc0-25ee-414e-abeb-a67d341e42e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[8]/following::div[2]</value>
      <webElementGuid>2c5ef760-ad2b-470a-b746-1d86858319f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명자1.전화번호'])[1]/following::div[21]</value>
      <webElementGuid>293e68ac-e73d-40ea-86ef-d0f27a312ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[6]/div</value>
      <webElementGuid>796b3554-9c15-4f6b-a76f-4c8356c7c0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cell-0-서명자1-이메일' and (text() = '필수 입력값이에요.' or . = '필수 입력값이에요.')]</value>
      <webElementGuid>5b172653-ac96-4498-b651-7954f2bf1d2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
