<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>임시저장_한컴싸인 아이콘</name>
   <tag></tag>
   <elementGuidId>40417879-24b4-4fdf-9e32-5bc2b5f8427e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;한컴싸인&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='create_task_title']/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>484f7b6f-348f-40ee-aa48-757be99dca00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>5cd5a41b-be0a-4056-9725-39e82a6696fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.stg.hancomsign.com/20230330/v1/images/ic-snb-logo.svg</value>
      <webElementGuid>0f457f4c-5e2f-49b4-aa87-726077fdf7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>한컴싸인</value>
      <webElementGuid>e321ae2f-16c8-48ce-bf2f-5596b64f6fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_task_title&quot;)/div[@class=&quot;MuiBox-root css-70qvj9&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeMedium css-1n2jc4i&quot;]/img[1]</value>
      <webElementGuid>dfcc8231-2d31-4cec-8208-d4febe6a6e08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_task_title']/div/button/img</value>
      <webElementGuid>bf512edf-de7c-4ca6-b726-6de3eae9a52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='한컴싸인']</value>
      <webElementGuid>28fb5eb0-cda1-46b2-bf88-32d3afc5bc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>efa2a64f-825b-443b-8660-351ec9773144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.stg.hancomsign.com/20230330/v1/images/ic-snb-logo.svg' and @alt = '한컴싸인']</value>
      <webElementGuid>57d042c0-d369-49eb-a82a-93cc845b561c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
