<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>임시저장_편집 버튼</name>
   <tag></tag>
   <elementGuidId>fd82770e-0800-4bd0-b643-75275e384872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Assign-Fields-Edit-GetSignatures</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>992958f2-6cc9-406a-9aec-fad16922e08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assign-Fields-Edit-GetSignatures</value>
      <webElementGuid>f9e19a2f-b288-43e3-afb9-ef8c527899a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styledCreate__BtnEdit-sc-1e5ee0j-3 eFbBUR</value>
      <webElementGuid>eaa6426d-760a-4ccc-924d-8c3ffa9013e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>편집</value>
      <webElementGuid>d79e9ca2-4469-4041-9584-36262e1ec963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assign-Fields-Edit-GetSignatures&quot;)</value>
      <webElementGuid>9f3d6f12-db95-4410-a37b-b441eb183457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      <webElementGuid>4053d13b-dfac-4e5a-86b1-0a5f915f4c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div/div</value>
      <webElementGuid>e7f7273b-b21f-4b0f-b1a9-1ae4849dd8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='계속'])[1]/following::div[10]</value>
      <webElementGuid>be161b5b-74c8-4cd3-be1b-06ddf6bcb07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::div[3]</value>
      <webElementGuid>58d586ff-f40f-4cb4-9dd9-74b0370d568e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/preceding::div[31]</value>
      <webElementGuid>190fc765-45f4-4ede-9fb8-a5bf632f5ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='편집']/parent::*</value>
      <webElementGuid>bde11eaf-8231-4561-88dc-ba026d7d6562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div</value>
      <webElementGuid>e35a9fa3-bb7f-4a1f-8a20-0ced3dc77dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Assign-Fields-Edit-GetSignatures' and (text() = '편집' or . = '편집')]</value>
      <webElementGuid>407d9b04-ff94-44bb-84a5-8f0592c77bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
