<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>임시저장_관리 아이콘</name>
   <tag></tag>
   <elementGuidId>955b5d74-bd5e-4b69-af3c-8483f520ba69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task-more-box-37009</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'icon' and @aria-haspopup = 'true']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='task-more-box-37009']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b1b1f15-eb0a-4924-98f0-eff8e7eef9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1nlpkey</value>
      <webElementGuid>4bb61107-cef9-425e-9499-e4c512d26c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bda18198-31e1-4364-b55c-eb2e90eacdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>d39889b4-8156-448b-8657-b8c8bf7158a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task-more-box-37009</value>
      <webElementGuid>9805da7b-2a2e-4b3a-a21a-d199b6404011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>862ad7da-d771-498a-9d22-cbbcaa08127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-more-box-37009&quot;)</value>
      <webElementGuid>75e7ee04-3758-4155-82ad-5215d9284fe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='task-more-box-37009']</value>
      <webElementGuid>7c896002-a282-4c8a-a545-b4f9db1362ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/main/div/div/div/div[3]/div[4]/div/button</value>
      <webElementGuid>092466f8-67c0-45a9-9915-bb04b3e34fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='일시:'])[1]/following::button[1]</value>
      <webElementGuid>dec5716a-acfe-49d3-a05d-eb3b28563972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='서명 요청자:'])[1]/following::button[1]</value>
      <webElementGuid>75a254a2-a0f9-44d6-922f-613245a3323f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I'])[1]/preceding::button[4]</value>
      <webElementGuid>030eb201-687c-4605-abb9-5a8fe76f9ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인정보 처리방침'])[1]/preceding::button[4]</value>
      <webElementGuid>1be21244-c2e3-4226-985b-8c2e22dcff55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/button</value>
      <webElementGuid>47c82e7c-ac5a-4fbc-a376-f6b3ad80a0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'icon' and @id = 'task-more-box-37009']</value>
      <webElementGuid>76a3fff8-091d-49d2-a0b3-993a7722f8f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
