<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>컨텍스트 삭제위치</name>
   <tag></tag>
   <elementGuidId>3718b585-b842-456c-82a5-59a981d89300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.moveable-line.moveable-direction.moveable-w</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageContainer1']/div[3]/div[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;task-more-menu-36961&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiMenu-paper MuiPopover-paper MuiMenu-paper css-n6fbq3&quot;]/ul[@class=&quot;MuiList-root MuiList-padding MuiMenu-list css-r8u8y9&quot;]/li[@class=&quot;MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-19s4myt&quot;]/div[@class=&quot;MuiBox-root css-ih0h00&quot;][count(. | //*[@class = 'MuiBox-root css-ih0h00' and @aria-hidden = 'true']) = count(//*[@class = 'MuiBox-root css-ih0h00' and @aria-hidden = 'true'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bcf6b8d3-7727-4967-be5e-46ec4906d10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moveable-line moveable-direction moveable-w</value>
      <webElementGuid>e532cbf1-3116-498f-a25e-82cdf8b209a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContainer1&quot;)/div[@class=&quot;moveable-control-box   holder-JackRabbit_4a371400-72fd-11ee-8042-0f84e316391d Edit_moveable__ZDOSq rCSwtyrwf&quot;]/div[@class=&quot;moveable-line moveable-direction moveable-w&quot;]</value>
      <webElementGuid>595757a5-248e-40a8-a569-49ddf41c3564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8d49f50-6575-491e-ac14-9b007407ab43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rotation</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>15750550-2223-480d-82e5-e5ef38e52a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-line-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b4a0fdc8-877a-448d-b7b4-bbafa6978c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-direction</name>
      <type>Main</type>
      <value>w</value>
      <webElementGuid>23aacf57-3200-4057-8691-578f48da62ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageContainer1']/div[3]/div[6]</value>
      <webElementGuid>23d7d6ce-a740-4511-b1b9-c391b0ed256e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[6]</value>
      <webElementGuid>a474739a-a813-49b6-b023-96f939f3a0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task-more-menu-36961']/div[3]/ul/li[5]/div</value>
      <webElementGuid>610bf585-3af4-4c44-9c36-10642f933cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='삭제'])[1]//div[1]</value>
      <webElementGuid>d0db93a2-dc4f-4082-927e-2658731348fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='문서 보기'])[1]/following::div[1]</value>
      <webElementGuid>ff0ca5ee-ddff-4aa7-b380-793ed6f933fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div</value>
      <webElementGuid>6e06dc8d-340b-47e0-ad3f-cc022a7bc500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task-more-menu-36961']/div</value>
      <webElementGuid>314880ed-a6f8-4f04-a05e-3e92ea09f0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>997a9af6-f30a-43da-8053-15f5d0d64ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='avatar-positioned-menu']/div</value>
      <webElementGuid>a1fc6a1a-90b7-4b1b-98db-9aa6687b2f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='수정한 내용을 저장할까요?'])[1]/following::div[1]</value>
      <webElementGuid>d09de3c3-f96f-4342-a391-c4473690d405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='알림'])[1]/following::div[3]</value>
      <webElementGuid>520760d1-52e5-417b-9627-5bc9b373895c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>8d6a4a1d-7a44-4151-b4e1-2e47da5e4428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
