<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>편집 버튼</name>
   <tag></tag>
   <elementGuidId>2afff381-cc7c-4561-8c15-4449cebd541a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Assign-Fields-Edit-GetSignatures</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d6517ab-5ccf-497e-856f-be29e972bc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assign-Fields-Edit-GetSignatures</value>
      <webElementGuid>bb399619-dcac-45db-b954-520998053637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styledCreate__BtnEdit-sc-1e5ee0j-3 eFbBUR</value>
      <webElementGuid>df3e5dea-9821-4fbd-9c28-584403bf57cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>편집</value>
      <webElementGuid>1b268a66-eb52-4ab3-b746-4293029562dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assign-Fields-Edit-GetSignatures&quot;)</value>
      <webElementGuid>7cb80ca6-d340-43c0-b03d-c4c0597f8797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Assign-Fields-Edit-GetSignatures']</value>
      <webElementGuid>e2bc313e-248f-4ad9-aa16-481bf391c8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create_left_panel']/div[2]/div/div</value>
      <webElementGuid>2ae248a7-3de7-41bb-86f4-3fb4ba24ba43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='계속'])[1]/following::div[10]</value>
      <webElementGuid>044d886d-94bf-4509-bc39-f6249a743779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::div[3]</value>
      <webElementGuid>69330a9c-1dd0-4142-8156-418325e44cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/preceding::div[31]</value>
      <webElementGuid>8f82644c-34e0-42c5-8169-ba874bbc27b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='편집']/parent::*</value>
      <webElementGuid>381e4470-2f2b-4c55-be1f-920d8c4fccb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div</value>
      <webElementGuid>3ce98448-fb68-4c4f-a36f-91182214b287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Assign-Fields-Edit-GetSignatures' and (text() = '편집' or . = '편집')]</value>
      <webElementGuid>edf25667-410c-469b-836d-1beaa912908e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
