<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>프로필 아이콘</name>
   <tag></tag>
   <elementGuidId>3fa3a13b-68f5-42fc-ae5c-30e5e8ffe78d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1xoz5k8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-box']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f625a8bc-4cf0-48d7-bb7f-871c47ca2974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.stg.hancomsign.com/20220629/v1/images/avatar/avatar_00.png</value>
      <webElementGuid>85ab77ee-7339-43ef-b345-62f6865f3e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xoz5k8</value>
      <webElementGuid>1a02e01d-57b0-4372-b4bb-ffb3cda2b385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-box&quot;)/div[@class=&quot;css-1n0zp4h&quot;]/div[@class=&quot;css-1xoz5k8&quot;]</value>
      <webElementGuid>6a0ea9a5-6bbc-4a62-9ede-6720f0fb604e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-box']/div/div</value>
      <webElementGuid>65127996-b9d5-48b3-b431-0810e6634bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>ba016385-9ade-47c9-896d-df504922c217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@src = 'https://static.stg.hancomsign.com/20220629/v1/images/avatar/avatar_00.png']</value>
      <webElementGuid>53ef4d75-ce86-4d6f-84a6-b0fecb201087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
