<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>프로필 아이콘</name>
   <tag></tag>
   <elementGuidId>3fa3a13b-68f5-42fc-ae5c-30e5e8ffe78d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1xoz5k8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-box']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02ccb6b0-055d-4315-93db-c473ae59ad59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.stg.hancomsign.com/20220629/v1/images/avatar/avatar_00.png</value>
      <webElementGuid>006b4287-6252-42b4-a266-c0c863e81232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xoz5k8</value>
      <webElementGuid>5e05354f-069e-4bb0-a285-f71d48ff10c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-box&quot;)/div[@class=&quot;css-1n0zp4h&quot;]/div[@class=&quot;css-1xoz5k8&quot;]</value>
      <webElementGuid>a0380d2e-e91c-4bea-8a6a-db84aa1bfa55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-box']/div/div</value>
      <webElementGuid>03b63128-9ef6-455a-854c-79c329e12114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>ba5b4dd1-5803-428b-94b1-07e95971f940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@src = 'https://static.stg.hancomsign.com/20220629/v1/images/avatar/avatar_00.png']</value>
      <webElementGuid>3131386a-2b58-4f4f-9f87-91aa0e145231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
