<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>거부입력사유 필드</name>
   <tag></tag>
   <elementGuidId>c8f2546c-531b-4dad-b621-294833576116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@rows = '2' and @placeholder = '메시지를 입력하세요.']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-120</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='mui-120']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>07b6e68e-1bd6-4780-945d-ea98cf8c4d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>32f30491-68d5-4a75-a7e2-a66411dee9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e11a2910-97c0-47d1-8e0e-73ebe93666dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>메시지를 입력하세요.</value>
      <webElementGuid>6403da26-e69b-4d52-b775-7ace816b9602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-123ozb2</value>
      <webElementGuid>9a79e42e-4c4a-4d3c-bec3-a7466b0ab37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-120</value>
      <webElementGuid>7c1e7c91-f454-4d57-98f8-f05be36fe594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-120&quot;)</value>
      <webElementGuid>3d33611a-8f75-45f5-85fd-d089b24e1588</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mui-120']</value>
      <webElementGuid>efa8c9f7-9098-4602-83f4-72aa285448aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1505fd5a-517c-490f-be7a-8c71767a1345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '메시지를 입력하세요.' and @id = 'mui-120']</value>
      <webElementGuid>fa050a57-922a-4447-b675-10955af7abc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
