<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>거부입력사유 필드</name>
   <tag></tag>
   <elementGuidId>c8f2546c-531b-4dad-b621-294833576116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@rows = '2' and @placeholder = '메시지를 입력하세요.']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-120</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='mui-120']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a906ea4c-83a3-4598-931c-f55486cc84ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>91278336-7a18-4400-a430-33457dcf1766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4b0ff63-d863-4b5e-ab26-6e077591976f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>메시지를 입력하세요.</value>
      <webElementGuid>ae3a81bd-9400-48b8-8a3e-d338c9f0ca44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-123ozb2</value>
      <webElementGuid>21d3f112-7607-41f9-bf6d-2f2e7846ebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-120</value>
      <webElementGuid>7657c8d0-718e-4b96-afa7-cb8755a467be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-120&quot;)</value>
      <webElementGuid>e2fa5b40-e0b5-461d-b1fc-1850b8b3ec3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mui-120']</value>
      <webElementGuid>4bcbdb05-051a-411d-a05b-d1d6c9534674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>efdfc006-3bd1-41ea-a225-d77f8f3c6068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '메시지를 입력하세요.' and @id = 'mui-120']</value>
      <webElementGuid>12ab68b2-e800-400a-a8b1-17f90fe63e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
