<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>(1) (2)</name>
   <tag></tag>
   <elementGuidId>41535aa4-0be5-4bb8-bcdd-5550cbc80ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.styled__Input-sc-otvfr5-1.gywLlB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7640945a-71ab-45d7-a556-fa4325f511f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>서명</value>
      <webElementGuid>264a41fa-7be2-42b4-a879-4be52f9f55ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Input-sc-otvfr5-1 gywLlB</value>
      <webElementGuid>427b5814-a948-48fd-8c2b-e40d2fae1991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07&quot;)/div[@class=&quot;MuiBox-root css-uwwqev&quot;]/div[@class=&quot;styled__Wrapper-sc-lip6vl-0 jzzTRw&quot;]/div[@class=&quot;styled__Wrapper-sc-otvfr5-0 eYdKpa&quot;]/input[@class=&quot;styled__Input-sc-otvfr5-1 gywLlB&quot;]</value>
      <webElementGuid>d7ec0a2a-3c1e-4fce-8a77-e4d9c4539f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>daf2cd49-d4d2-41a1-af02-d5b225495428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07']/div[3]/div/div/input</value>
      <webElementGuid>465042a2-a9fb-41e2-a84d-f9149354e606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f3e108c9-1f00-4bc7-bcfc-7a2ab329568e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '서명']</value>
      <webElementGuid>2aae1654-141f-4e8f-9c1a-5783e782c45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_20961650-634e-11ee-82e7-938feedc214b']/div[3]/div/div/input</value>
      <webElementGuid>91fb523a-2247-4e81-807b-42ba011bd7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_956b8520-634c-11ee-85f6-91b2fef84634']/div[3]/div/div/input</value>
      <webElementGuid>1594a6d1-47d5-4901-b99d-b04f4fc47205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_b507ac20-634b-11ee-bded-8ffb8977919f']/div[3]/div/div/input</value>
      <webElementGuid>089880de-c6dc-4012-8b4c-725a2992e94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_161226e0-633c-11ee-bcf5-810e97b4681b']/div[3]/div/div/input</value>
      <webElementGuid>fd89ca91-1b17-420f-9307-89023ad3e918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
