<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>(1) (6)</name>
   <tag></tag>
   <elementGuidId>c24bb6ea-4b5d-44c2-bd3e-19c3cec8129a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-1ctavtd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df3f2195-8e0a-4909-9ebc-62a682abbaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1ctavtd</value>
      <webElementGuid>53da4777-6eb1-41d8-bf4d-c784e5f46a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소</value>
      <webElementGuid>b1afdc8f-463c-44c7-a903-6f1af4a33670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-h80ire&quot;]/div[@class=&quot;MuiBox-root css-kdfcgt&quot;]/div[@class=&quot;MuiBox-root css-1ctavtd&quot;]</value>
      <webElementGuid>4fec4cdf-2366-4729-acae-b0757d64a355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div</value>
      <webElementGuid>9dfab1cb-c6a2-4098-a06f-12bd03c7586d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>f2061a2e-de38-4a1a-a97b-0a218e10e14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소' or . = '1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소')]</value>
      <webElementGuid>ba9fb479-c19d-44ee-ab17-69ef73c90ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
