<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>도장이미지</name>
   <tag></tag>
   <elementGuidId>10fc9799-5a0b-4546-8d20-530ed4dd6f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#245</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='245']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5d825cb-6350-463f-b7d2-2fb283882bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>245</value>
      <webElementGuid>1114ea8e-25d2-4fda-acc2-dbcbf79a9026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__StampWrapper-sc-1cpb15e-2 iwDviH</value>
      <webElementGuid>0030bf12-9017-47fc-b52e-bc0e10979adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;245&quot;)</value>
      <webElementGuid>a53f9295-83a9-445d-8e5c-7f3031a64345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='245']</value>
      <webElementGuid>43ea77ca-faa4-48eb-957d-e782c18b9512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도장 및 서명 이미지'])[1]/following::div[5]</value>
      <webElementGuid>6ddee9bc-c2b9-48bd-8efa-b395b4a3a74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '245', '&quot;', ')')])[1]/following::div[14]</value>
      <webElementGuid>6422cee8-f0a1-4f2c-b00c-b6e5efb319fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[2]/preceding::div[9]</value>
      <webElementGuid>6eb1a1db-c355-41a5-a031-7fa1d4fa8595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='적용'])[1]/preceding::div[9]</value>
      <webElementGuid>3ff8beab-5ef7-40d8-bfbb-cd8a375673a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>16d612cd-dc9d-4d68-9f24-3739a3f0b93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '245']</value>
      <webElementGuid>69f79d62-6937-465c-a152-31262d4ca2eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
