<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>도장이미지</name>
   <tag></tag>
   <elementGuidId>10fc9799-5a0b-4546-8d20-530ed4dd6f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#245</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='245']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe182842-ff36-4fc8-b124-82d5dd7a2026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>245</value>
      <webElementGuid>8aadfccc-5554-4feb-aac0-f73085450919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__StampWrapper-sc-1cpb15e-2 iwDviH</value>
      <webElementGuid>9c99535c-1772-49a4-9253-7eab2e183416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;245&quot;)</value>
      <webElementGuid>9af2cfa8-85b1-4338-a011-d92245908eb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='245']</value>
      <webElementGuid>51fecd7f-a8be-4a64-99b3-85b9ef51d258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도장 및 서명 이미지'])[1]/following::div[5]</value>
      <webElementGuid>c9ed14e4-245a-4e04-9064-797df15becf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '245', '&quot;', ')')])[1]/following::div[14]</value>
      <webElementGuid>d04c932b-354d-42a4-a04d-ab0085dbf965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[2]/preceding::div[9]</value>
      <webElementGuid>ac7b1788-5597-43e2-bcba-f8ff54a433ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='적용'])[1]/preceding::div[9]</value>
      <webElementGuid>0ef59184-d9ae-4358-810f-3c9f2bcc6980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>b68ca7cb-f1bc-453e-b340-75374ade88fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '245']</value>
      <webElementGuid>1f9228ca-b5a4-439d-98c6-d588b699ea97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
