<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명하기영역</name>
   <tag></tag>
   <elementGuidId>484f001f-18ef-44ce-ba03-83c9dde8cc1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styled__Input-sc-otvfr5-1.gywLlB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06f254ea-c8ce-4574-9ebf-f00afe878fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>서명</value>
      <webElementGuid>414c4d85-5df2-48f9-8825-17d200a5512b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Input-sc-otvfr5-1 gywLlB</value>
      <webElementGuid>a882f697-b500-477f-96f7-7de1a079882a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07&quot;)/div[@class=&quot;MuiBox-root css-uwwqev&quot;]/div[@class=&quot;styled__Wrapper-sc-lip6vl-0 jzzTRw&quot;]/div[@class=&quot;styled__Wrapper-sc-otvfr5-0 eYdKpa&quot;]/input[@class=&quot;styled__Input-sc-otvfr5-1 gywLlB&quot;]</value>
      <webElementGuid>f5668ca1-e81c-4804-8d85-a87db8ee335e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>7d7aaaf6-33ca-4cd3-9682-b3b0877624ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07']/div[3]/div/div/input</value>
      <webElementGuid>4b84425a-34db-4d6f-8b7d-6c8259d90cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d2a11eff-01bf-49db-b328-da432ba75e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '서명']</value>
      <webElementGuid>de756309-243e-45a3-af5e-bdea8b8f144c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_20961650-634e-11ee-82e7-938feedc214b']/div[3]/div/div/input</value>
      <webElementGuid>8077598f-c1be-43e2-88bd-85977e4deb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_956b8520-634c-11ee-85f6-91b2fef84634']/div[3]/div/div/input</value>
      <webElementGuid>643b3674-4595-41ba-ad6c-ab2340e1e9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_b507ac20-634b-11ee-bded-8ffb8977919f']/div[3]/div/div/input</value>
      <webElementGuid>300c9558-aab4-4a7b-a7d6-95c512f83fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_161226e0-633c-11ee-bcf5-810e97b4681b']/div[3]/div/div/input</value>
      <webElementGuid>2a3cd872-b2be-48bc-9c37-a4feb81ad462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
