<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명란</name>
   <tag></tag>
   <elementGuidId>34a4dec6-6651-45c4-9cdd-e98e38e603fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signInput-JackRabbit_223dd2e0-634e-11ee-82e7-938feedc214b']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styled__Wrapper-sc-ht1d3s-0.hTsDmN.chkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0bd49c2-31cf-4e2c-a1f0-ec49769c58c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>55662</value>
      <webElementGuid>d2ca881e-f958-4c36-bfef-4b752d1d9116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Wrapper-sc-ht1d3s-0 hTsDmN chkbox</value>
      <webElementGuid>eef86018-a211-47c5-88c4-beb2ab7245f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInput-JackRabbit_223dd2e0-634e-11ee-82e7-938feedc214b&quot;)/div[@class=&quot;styled__Wrapper-sc-ht1d3s-0 hTsDmN chkbox&quot;]</value>
      <webElementGuid>19e1ac9c-ed5e-478d-b8f5-e9a8ed2413cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_223dd2e0-634e-11ee-82e7-938feedc214b']/div[2]</value>
      <webElementGuid>4b5652fe-1a38-4745-9658-415d59765ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[2]</value>
      <webElementGuid>fe3ad2d4-f450-405c-9749-fa1f626d47ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도장 및 서명 이미지'])[1]/following::div[2]</value>
      <webElementGuid>e13ae434-e435-4cea-bddf-8a43eb2c68db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='필수 항목이에요.'])[1]/following::div[7]</value>
      <webElementGuid>4941f947-1fdc-45bf-a2ed-9204e8955f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[2]/preceding::div[10]</value>
      <webElementGuid>ce0d50c3-f217-4fa3-a365-a3ef37ea6660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='적용'])[1]/preceding::div[10]</value>
      <webElementGuid>ab3a6146-55f5-4933-8da5-4968fb8aca44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/div</value>
      <webElementGuid>bf10caee-1057-4fc0-95f9-b5fa155fe825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도장 및 서명 이미지'])[1]/following::div[3]</value>
      <webElementGuid>198d8cf8-c852-4a21-91c6-a8ba46a83b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::div[14]</value>
      <webElementGuid>5e4b08fb-43b4-475e-9b1a-a5654ac731e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[2]/preceding::div[7]</value>
      <webElementGuid>2a19b99e-3efc-4fd8-bf5b-0265953953fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='적용'])[1]/preceding::div[7]</value>
      <webElementGuid>86e34074-281d-41d3-a04a-eb8fb41ece3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div/div</value>
      <webElementGuid>eb855c41-2b5e-443b-b69c-cd382754d71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::div[13]</value>
      <webElementGuid>ccabb1d5-2e4f-43cc-aaca-793b013bc319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[2]/preceding::div[8]</value>
      <webElementGuid>82e95fd2-6c71-4701-a608-3225d8c07637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='적용'])[1]/preceding::div[8]</value>
      <webElementGuid>be4da776-5601-41fa-b47d-9574293c3468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div</value>
      <webElementGuid>979a8eff-07b6-4bbb-9c42-cd15ef4e67f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
