<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명하기영역</name>
   <tag></tag>
   <elementGuidId>484f001f-18ef-44ce-ba03-83c9dde8cc1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styled__Input-sc-otvfr5-1.gywLlB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9590bf7c-9f02-4720-9a77-559e82b763fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>서명</value>
      <webElementGuid>64ba4eb3-1e54-4151-a059-4ec70116716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Input-sc-otvfr5-1 gywLlB</value>
      <webElementGuid>d06fa2c0-91f1-442d-a213-d03d19d7f08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07&quot;)/div[@class=&quot;MuiBox-root css-uwwqev&quot;]/div[@class=&quot;styled__Wrapper-sc-lip6vl-0 jzzTRw&quot;]/div[@class=&quot;styled__Wrapper-sc-otvfr5-0 eYdKpa&quot;]/input[@class=&quot;styled__Input-sc-otvfr5-1 gywLlB&quot;]</value>
      <webElementGuid>4e7a34a3-8556-44ce-9739-4915bfe0efe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>448fd5b7-b3ca-46d9-bbfa-f4af3b55f24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07']/div[3]/div/div/input</value>
      <webElementGuid>4fc94a73-ecd2-45b4-bdb0-a4588a9c3501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>00c58316-eddd-4803-972e-11c2066ef57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '서명']</value>
      <webElementGuid>96ef87f8-b68a-4af3-9e9a-050807e644aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_20961650-634e-11ee-82e7-938feedc214b']/div[3]/div/div/input</value>
      <webElementGuid>30c8b2e4-1a64-4f7d-82da-f399f3470b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_956b8520-634c-11ee-85f6-91b2fef84634']/div[3]/div/div/input</value>
      <webElementGuid>c8a0e873-dc69-4c3b-861a-e706809c945c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_b507ac20-634b-11ee-bded-8ffb8977919f']/div[3]/div/div/input</value>
      <webElementGuid>32cda587-3e95-48e8-9805-43d41fafe26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_161226e0-633c-11ee-bcf5-810e97b4681b']/div[3]/div/div/input</value>
      <webElementGuid>5e2b949a-93d6-478f-9473-0aef62343899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
