<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명 캔버스 영역</name>
   <tag></tag>
   <elementGuidId>2983e8fb-e0b8-4e83-9602-ce61ad78b734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.react-pdf__Page__canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageContainer1']/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>3eff114f-4af1-46d8-b9c7-b50ee6de7fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-pdf__Page__canvas</value>
      <webElementGuid>ba7c633c-6836-4f0f-9bf8-03b30f3cb571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1606</value>
      <webElementGuid>adf345db-a975-4288-b764-777b43115f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2270</value>
      <webElementGuid>99f5216d-ef3d-4ce8-ac06-dac2456c5ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContainer1&quot;)/div[@class=&quot;react-pdf__Page&quot;]/canvas[@class=&quot;react-pdf__Page__canvas&quot;]</value>
      <webElementGuid>d7ca592f-0cde-444b-b4ea-03cefa0d05ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageContainer1']/div/canvas</value>
      <webElementGuid>fcc8e5d8-e4ba-4292-a913-71bc6c7337e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>c22aa703-6c3c-4101-ba68-9dd7258fc775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
