<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명 캔버스 영역</name>
   <tag></tag>
   <elementGuidId>2983e8fb-e0b8-4e83-9602-ce61ad78b734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.react-pdf__Page__canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageContainer1']/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>892f451b-00ea-4643-96e1-f941f922b5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-pdf__Page__canvas</value>
      <webElementGuid>48100c3f-a269-487e-87fc-de51e669632f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1606</value>
      <webElementGuid>112d1df6-37d7-46b7-a646-731736d193d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2270</value>
      <webElementGuid>a815e04c-74e6-4c50-b6f0-2cd54a155d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContainer1&quot;)/div[@class=&quot;react-pdf__Page&quot;]/canvas[@class=&quot;react-pdf__Page__canvas&quot;]</value>
      <webElementGuid>6de01ba5-c666-4cc9-a229-c7df9daaf009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageContainer1']/div/canvas</value>
      <webElementGuid>ddb11cd9-f09e-49c2-801a-65b34d0e819e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>6737e888-0ee1-4af5-8cb9-b9068adca2bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
