<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명양도_도장선택</name>
   <tag></tag>
   <elementGuidId>076e6087-e1cc-4998-b483-51734be5cd1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#247</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='247']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52ef623d-8ef9-42bb-a685-de5511232f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>247</value>
      <webElementGuid>48f8d4ff-9567-4ce7-ba3b-eefd09c9dd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__StampWrapper-sc-1cpb15e-2 znvYv</value>
      <webElementGuid>5ffaadf0-5717-41f8-9619-2570e95ff84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;247&quot;)</value>
      <webElementGuid>5838754f-3c62-471b-a6ab-b54c237e9664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='247']</value>
      <webElementGuid>30a61d82-3348-4c4e-a65e-76c183365847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도장 및 서명 이미지'])[1]/following::div[5]</value>
      <webElementGuid>c9ee6b4b-87f0-4c24-8a46-dddd332b5bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='필수 항목이에요.'])[1]/following::div[10]</value>
      <webElementGuid>ea3fa95b-3bdb-401f-8fa6-c7e28263e3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[2]/preceding::div[7]</value>
      <webElementGuid>f206948d-7262-42fb-b7b5-c22db9b4e87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='적용'])[1]/preceding::div[7]</value>
      <webElementGuid>62653b9a-6542-4115-8f87-37aff055117c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>58dc9500-2448-4383-9631-a06f331668e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '247']</value>
      <webElementGuid>8fe86e13-6bb2-4288-a482-353489d33178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
