<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>서명하기영역</name>
   <tag></tag>
   <elementGuidId>484f001f-18ef-44ce-ba03-83c9dde8cc1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styled__Input-sc-otvfr5-1.gywLlB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2392ef62-3da6-41e9-b538-a5303dd15d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>서명</value>
      <webElementGuid>774d288c-9562-4eeb-a8c8-e112aeddde2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__Input-sc-otvfr5-1 gywLlB</value>
      <webElementGuid>5eafd943-07a4-4770-b580-914f12a96270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07&quot;)/div[@class=&quot;MuiBox-root css-uwwqev&quot;]/div[@class=&quot;styled__Wrapper-sc-lip6vl-0 jzzTRw&quot;]/div[@class=&quot;styled__Wrapper-sc-otvfr5-0 eYdKpa&quot;]/input[@class=&quot;styled__Input-sc-otvfr5-1 gywLlB&quot;]</value>
      <webElementGuid>289759b4-0af6-412d-9240-c1438437abea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>0ac4e542-585e-4051-aea4-8f408a56c467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_e9215220-6ccb-11ee-8bc3-e3971b06eb07']/div[3]/div/div/input</value>
      <webElementGuid>03c3b601-7fc0-4f2d-9e1e-6f430c20e4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9f61b343-5150-4467-8f28-7c7b874170ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '서명']</value>
      <webElementGuid>72f23d63-3ef9-45f7-8760-3f2ca29126df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_20961650-634e-11ee-82e7-938feedc214b']/div[3]/div/div/input</value>
      <webElementGuid>84b7c05b-ad88-4c4b-b4f6-7d343eeca6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_956b8520-634c-11ee-85f6-91b2fef84634']/div[3]/div/div/input</value>
      <webElementGuid>c6aea640-971a-4f94-824f-90c60ece2fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_b507ac20-634b-11ee-bded-8ffb8977919f']/div[3]/div/div/input</value>
      <webElementGuid>b2542425-769b-4f67-ab05-65b8a53144e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInput-JackRabbit_161226e0-633c-11ee-bcf5-810e97b4681b']/div[3]/div/div/input</value>
      <webElementGuid>d167f772-fff7-4ef2-9a91-ce87e7ee0814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
