<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>하단 메뉴 영역</name>
   <tag></tag>
   <elementGuidId>0562eaa3-e979-4ecb-af25-192c373b9fd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-1ctavtd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61e36c3b-2558-468b-a864-947141858576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1ctavtd</value>
      <webElementGuid>d3422250-c3d2-413e-9b42-0d5e41738fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소</value>
      <webElementGuid>29a93851-3f82-45df-9cc6-48d3202de2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-h80ire&quot;]/div[@class=&quot;MuiBox-root css-kdfcgt&quot;]/div[@class=&quot;MuiBox-root css-1ctavtd&quot;]</value>
      <webElementGuid>2db95d8c-92d0-428a-99f3-ad7f5f526151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div</value>
      <webElementGuid>be384579-5e1a-4dc0-8f8e-c771b9f91ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>818a2c18-0259-4acb-8309-82fcd8557e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소' or . = '1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소')]</value>
      <webElementGuid>42ae4932-e98f-48c2-b7e5-be74e1f91302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
