<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>하단 메뉴 영역</name>
   <tag></tag>
   <elementGuidId>0562eaa3-e979-4ecb-af25-192c373b9fd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-1ctavtd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94f2a78e-62d1-4508-be92-41fc28795f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1ctavtd</value>
      <webElementGuid>43ecaf78-1b24-4488-9cfe-d6415851fe07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소</value>
      <webElementGuid>2b5644c2-b4dd-4a9f-989c-285de8c426ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-h80ire&quot;]/div[@class=&quot;MuiBox-root css-kdfcgt&quot;]/div[@class=&quot;MuiBox-root css-1ctavtd&quot;]</value>
      <webElementGuid>837e0db0-eb4d-4104-ab11-6254cfde0b4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div</value>
      <webElementGuid>c203c77a-36f5-4848-9ab4-6bcbef3d2170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>7a2e3096-1989-45eb-a6d7-92211c9094f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소' or . = '1문서 내용 확인2내용 입력3문서 서명 완료모든 입력이 완료되었어요. [입력 완료]를 선택하여 제출하세요.입력 완료취소')]</value>
      <webElementGuid>c7a6bf98-be40-4c9f-adb9-9b9d68381a56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
